### ISSUE TITLE
程式碼

### ISSUE THREAD

**Issue by wst0310** [eyelash94500/python_fin_azure#1]
請問有P113~P117的程式碼嗎
以利推敲
謝謝

**Comment by eyelash94500** [comment]
@wst0310 是把歷史資料放到資料庫那邊嗎？
我這邊整理一下再push上來

**Comment by wst0310** [comment]
對
到這邊就卡住了
麻煩您了

**Comment by eyelash94500** [comment]
已增加：
* 把歷史資料放入資料庫：[stock_history.py](https://github.com/eyelash94500/python_fin_azure/blob/master/code/ch3/stock_history.py)
* 每日市場資料放入資料庫：[get_market_info.py](https://github.com/eyelash94500/python_fin_azure/blob/master/code/ch3/get_market_info.py)

看來這個部分應該要多描述，進展有點太快，如果有疑問的地方可以繼續提出

**Comment by wst0310** [comment]
請問：stock_history.py中
row.high if pd.notnull(row.high) == float('nan') else 0,
row.low if pd.notnull(row.low) == float('nan') else 0,
row.close if pd.notnull(row.close) == float('nan') else 0,
row.volume if pd.notnull(row.volume) == float('nan') else 0
是否有問題
資料表寫入的值都為0

**Comment by wst0310** [comment]
另外，
row.volume if pd.notnull(row.volume) == float('nan') else 0
如果拿掉== float('nan') 會出現
(1265, "Data truncated for column 'Volume' at row 1")
沒拿掉會寫入0
再麻煩協助
謝謝

**Comment by wst0310** [comment]
我將date = '202205'改成date = '202204'
還是取得5月的資料
不知是何原因

**Comment by eyelash94500** [comment]
首先，`row.volume if pd.notnull(row.volume) == float('nan') else 0`
是在說檢查欄位中是否有空值，因有空值放進去會發生資料寫入錯誤，
所以當值為空值（nan）時，就給予預設值「0」

如果表示都為「0」，應該是格式有更變，在放入pandas 時被放入空值

**Comment by eyelash94500** [comment]
> 我將date = '202205'改成date = '202204' 還是取得5月的資料 不知是何原因

這邊是範例沒有寫好，已修改成「年月日」格式。他會取得該日期所屬月份的資訊，例如：20220406，就會取得 2022 年 4 月交易資訊。

注意的是，他的查詢有所限制：
`
{
    "stat": "查詢日期小於99年1月4日，請重新查詢!"
}
`
